// Generated by Wrangler on Mon Aug 05 2024 11:28:28 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

export interface Env {
	ALLOWED_ORIGINS: string[];
	EMAIL: string;
	FORM_BINDING: SendEmail;
}
