// Generated by Wrangler on Mon Aug 05 2024 11:28:28 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

export interface Env {
	ALLOWED_ORIGINS: string[];
	SENDGRID_URL: string
	SENDGRID_API_KEY: string
	SENDGRID_VERIFIED_SENDER: string
}
