#:schema node_modules/wrangler/config-schema.json
name = "mailing"
main = "src/index.ts"
compatibility_date = "2024-07-29"
node_compat = true

[vars]
ALLOWED_ORIGINS=['*']
SENDGRID_API_KEY="SOME_SENDGRID_API_KEY"
SENDGRID_URL="https://api.sendgrid.com/v3/mail/send"
SENDGRID_VERIFIED_SENDER="verified-sender@example.com"