#:schema node_modules/wrangler/config-schema.json
name = "mailing"
main = "src/index.ts"
compatibility_date = "2024-07-29"
node_compat = true
send_email = [{type = "send_email", name = "FORM_BINDING", destination_address = "some-email@example.com"}]

[vars]
ALLOWED_ORIGINS=['*']
EMAIL="some-email@example.com"
