name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or whichever version you're using

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # or whichever version you prefer

      - name: Update wrangler.toml
        run: |
          sed -i 's/some-email@example.com/${{ secrets.EMAIL }}/g' wrangler.toml
          sed -i 's/ALLOWED_ORIGINS=\[.*\]/ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}/g' wrangler.toml
      
      - name: Install dependencies
        run: pnpm install

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          EMAIL: ${{ secrets.EMAIL }}
  
